### PR TITLE
[start Ft#162160424]landing page commit

### PR DESCRIPTION
**Pull request by scott-kenya**
**What does this PR do?**
It has the markup and styling for the site's landing page
**Descriptions of the tasks to be completed?**
Have a markup for the landing page combined with styling configured such that all the elements in the site are responsive
**How should this be manually tested?**
After cloning the repo, cd into it and try to load the index.html file on your browser
Pivotal tracker story
#162160424
index

### CODE REVIEW

**Comment by MainaKamau92** [comment]
Looks good.

**Comment by MainaKamau92** [comment]
Your PR format is good

**Comment by MainaKamau92** [comment]
If you don't mind i'd like to borrow your format

**Comment by scott-kenya** [comment]
Feel free brother.

**Comment by MainaKamau92** [comment]
Thanks man, i am on my way there, we can go through those tough topics

**Comment by scott-kenya** [comment]
On my way too. Lets unblock each other

**Pull request merged**
